# Generated by Django 2.2.6 on 2019-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('genreid', models.CharField(blank=True, db_column='genreID', max_length=40, null=True, unique=True)),
                ('genrename', models.TextField(blank=True, db_column='genreName', null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('imgurl', models.TextField(blank=True, db_column='imgUrl', null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magnets',
            fields=[
                ('ma_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('addtime', models.DateField(blank=True, db_column='addTime', null=True)),
            ],
            options={
                'db_table': 'magnets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MG',
            fields=[
                ('m_g_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'm_g',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('avnum', models.CharField(blank=True, db_column='avNum', max_length=40, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('coverimgurl', models.TextField(blank=True, db_column='coverImgUrl', null=True)),
                ('thumbimgurl', models.TextField(blank=True, db_column='thumbImgUrl', null=True)),
                ('release', models.DateField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('producer', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MS',
            fields=[
                ('m_s_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'm_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('starid', models.CharField(blank=True, db_column='starID', max_length=40, null=True, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('cups', models.TextField(blank=True, null=True)),
                ('bust', models.IntegerField(blank=True, null=True)),
                ('waist', models.IntegerField(blank=True, null=True)),
                ('hip', models.IntegerField(blank=True, null=True)),
                ('birthplace', models.TextField(blank=True, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stars',
                'managed': False,
            },
        ),
    ]
